#ifndef ENUMS_H
#define ENUMS_H

enum TOOL {PENCIL, ERASER, CIRCLE, TRIANGLE, RECTANGLE, POLYGON, SENDTOFRONT, SENDTOBACK, PLUS, MINUS, SELECTOR};

enum COLOR {RED, ORANGE, YELLOW, GREEN, BLUE, INDIGO, VIOLET, RGB};

enum ACTION {NONE, CLEAR, FRONT, BACK, INCREASE, DECREASE};

#endif